add calico certs as a requirement for kubelet (#101)
* add-calico-certs-as-requirement

* fix api-certs

* fix endline

* add wait-for-domains as req for all certs units

* add failsafe to certs units

* add failsafe to get-vault-ca unit

* ignore invalid ssl for get-vault-ca

* add-calico-certs-as-requirement

diff --git a/ignition/aws/master.yaml.tmpl b/ignition/aws/master.yaml.tmpl
--- a/ignition/aws/master.yaml.tmpl
+++ b/ignition/aws/master.yaml.tmpl
@@ -1638,7 +1638,11 @@ storage:
                   exit
           fi
           echo Connecting to $1
-          echo -n | openssl s_client -showcerts -connect $1 2>err.txt 1>out.txt
+          while ! `echo -n | openssl s_client -showcerts -connect $1 2>err.txt 1>out.txt`
+          do
+                sleep 1s
+                echo retrying
+          done
           if [ "$?" -ne "0" ]
           then
                   cat err.txt
@@ -1797,6 +1801,7 @@ systemd:
       Environment=VAULT_ADDR=https://${VAULT_DOMAIN_NAME}:443
       Type=oneshot
       RemainAfterExit=yes
+      ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
       ExecStart=/bin/bash -c '\
          result=$(curl -o /etc/ssh/trusted-user-ca-keys.pem \
                    --header "X-Vault-Token: $VAULT_TOKEN" \
@@ -1864,8 +1869,8 @@ systemd:
     contents: |
       [Unit]
       Description=calico-certs
-      Requires=get-vault-ca.service k8s-setup-network-env.service docker.service
-      After=get-vault-ca.service k8s-setup-network-env.service docker.service
+      Requires=get-vault-ca.service k8s-setup-network-env.service docker.service wait-for-domains.service
+      After=get-vault-ca.service k8s-setup-network-env.service docker.service wait-for-domains.service
 
       [Service]
       EnvironmentFile=/etc/environment
@@ -1874,6 +1879,7 @@ systemd:
       Type=oneshot
       RemainAfterExit=yes
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/calico/
+      ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
       ExecStart=/usr/bin/docker run \
       --net=host \
       -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
@@ -1909,6 +1915,7 @@ systemd:
       Type=oneshot
       RemainAfterExit=yes
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/etcd/
+      ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
       ExecStart=/usr/bin/docker run \
       --net=host \
       -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
@@ -2033,8 +2040,8 @@ systemd:
       [Unit]
       Description=k8s-kubelet
       StartLimitIntervalSec=0
-      Requires=k8s-setup-network-env.service docker.service
-      After=k8s-setup-network-env.service docker.service
+      Requires=k8s-setup-network-env.service docker.service calico-certs.service api-certs.service
+      After=k8s-setup-network-env.service docker.service calico-certs.service api-certs.service
 
       [Service]
       Restart=always
@@ -2103,8 +2110,8 @@ systemd:
     contents: |
       [Unit]
       Description=api-certs
-      Requires=get-vault-ca.service k8s-setup-network-env.service docker.service
-      After=get-vault-ca.service k8s-setup-network-env.service docker.service
+      Requires=get-vault-ca.service k8s-setup-network-env.service docker.service wait-for-domains.service
+      After=get-vault-ca.service k8s-setup-network-env.service docker.service wait-for-domains.service
 
       [Service]
       EnvironmentFile=/etc/environment
@@ -2114,7 +2121,20 @@ systemd:
       Type=oneshot
       RemainAfterExit=yes
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/
-      ExecStartPre=/bin/bash -c 'export rsa_key=$(docker run --rm -i -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt --net host --privileged=true -e VAULT_ADDR -e VAULT_TOKEN giantswarm/docker-vault:0.1.0 read -field=key secret/g8s_sa_sign_key 2>/dev/null); echo -e "-----BEGIN RSA PRIVATE KEY-----\n$rsa_key\n-----END RSA PRIVATE KEY-----" > /etc/kubernetes/ssl/service-account-key.pem'
+      ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
+      ExecStartPre=/bin/bash -c '\
+        export rsa_key=$(\
+        docker run --rm -i\
+        -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt\
+        --net host\
+        --privileged=true\
+        -e VAULT_ADDR\
+        -e VAULT_TOKEN\
+        quay.io/giantswarm/vault:0.9.3\
+        read -field=key secret/g8s_sa_sign_key 2>/dev/null\
+       );\
+       [ -z "$rsa_key" ] && echo "Failed to fetch g8s_sa_key" && exit 1 || echo "Sucesfully retrieved g8s_sa_key";\
+        echo -e "-----BEGIN RSA PRIVATE KEY-----\n$rsa_key\n-----END RSA PRIVATE KEY-----" > /etc/kubernetes/ssl/service-account-key.pem'
       ExecStart=/usr/bin/docker run \
       --net=host \
       -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
