Add retry logic into certs units (#107)
* Remove scheduler leftover

* Add additional check for certs services

diff --git a/ignition/aws/master.yaml.tmpl b/ignition/aws/master.yaml.tmpl
--- a/ignition/aws/master.yaml.tmpl
+++ b/ignition/aws/master.yaml.tmpl
@@ -1880,22 +1880,30 @@ systemd:
       RemainAfterExit=yes
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/calico/
       ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
-      ExecStart=/usr/bin/docker run \
-      --net=host \
-      -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
-      -v /etc/kubernetes/ssl/calico/:/etc/kubernetes/ssl/calico/ \
-      quay.io/giantswarm/certctl:b07d0913d5cb369a6b605394bdd4be4633451be9 \
-      issue \
-      --vault-addr=https://${VAULT_DOMAIN_NAME} \
-      --vault-token=$${VAULT_TOKEN} \
-      --cluster-id=g8s \
-      --common-name=${ETCD_DOMAIN_NAME} \
-      --ttl=8760h \
-      --crt-file=/etc/kubernetes/ssl/calico/client-crt.pem \
-      --ip-sans=127.0.0.1,${DEFAULT_IPV4} \
-      --alt-names=localhost \
-      --key-file=/etc/kubernetes/ssl/calico/client-key.pem \
-      --ca-file=/etc/kubernetes/ssl/calico/client-ca.pem
+      ExecStart=/bin/bash -c '\
+        RETRY=3;\
+        while [ -z "$result"] && [ $RETRY -gt 0 ]; do\
+        sleep 2s; echo "Trying to issue calico certs...";\
+        let RETRY=$RETRY-1;\
+        export result=$(\
+          /usr/bin/docker run \
+          --net=host \
+          -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
+          -v /etc/kubernetes/ssl/calico/:/etc/kubernetes/ssl/calico/ \
+          quay.io/giantswarm/certctl:b07d0913d5cb369a6b605394bdd4be4633451be9 \
+          issue \
+          --vault-addr=https://${VAULT_DOMAIN_NAME} \
+          --vault-token=$${VAULT_TOKEN} \
+          --cluster-id=g8s \
+          --common-name=${ETCD_DOMAIN_NAME} \
+          --ttl=8760h \
+          --crt-file=/etc/kubernetes/ssl/calico/client-crt.pem \
+          --ip-sans=127.0.0.1,${DEFAULT_IPV4} \
+          --alt-names=localhost \
+          --key-file=/etc/kubernetes/ssl/calico/client-key.pem \
+          --ca-file=/etc/kubernetes/ssl/calico/client-ca.pem); \
+        done; \
+        [ -z "$result" ] && echo "Failed to issue calico certs." && exit 1 || echo "Successfully issued calico certs.";'
       ExecStop=/usr/bin/rm -rf /etc/kubernetes/ssl/calico/
 
       [Install]
@@ -1916,22 +1924,30 @@ systemd:
       RemainAfterExit=yes
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/etcd/
       ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
-      ExecStart=/usr/bin/docker run \
-      --net=host \
-      -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
-      -v /etc/kubernetes/ssl/etcd/:/etc/kubernetes/ssl/etcd/ \
-      quay.io/giantswarm/certctl:b07d0913d5cb369a6b605394bdd4be4633451be9 \
-      issue \
-      --vault-addr=https://${VAULT_DOMAIN_NAME} \
-      --vault-token=$${VAULT_TOKEN} \
-      --cluster-id=g8s \
-      --common-name=${ETCD_DOMAIN_NAME} \
-      --ttl=8760h \
-      --crt-file=/etc/kubernetes/ssl/etcd/server-crt.pem \
-      --ip-sans=127.0.0.1,${DEFAULT_IPV4} \
-      --alt-names=localhost \
-      --key-file=/etc/kubernetes/ssl/etcd/server-key.pem \
-      --ca-file=/etc/kubernetes/ssl/etcd/server-ca.pem
+      ExecStart=/bin/bash -c '\
+        RETRY=3;\
+        while [ -z "$result"] && [ $RETRY -gt 0 ]; do\
+        sleep 2s; echo "Trying to issue etcd certs...";\
+        let RETRY=$RETRY-1;\
+        export result=$(\
+          /usr/bin/docker run \
+          --net=host \
+          -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
+          -v /etc/kubernetes/ssl/etcd/:/etc/kubernetes/ssl/etcd/ \
+          quay.io/giantswarm/certctl:b07d0913d5cb369a6b605394bdd4be4633451be9 \
+          issue \
+          --vault-addr=https://${VAULT_DOMAIN_NAME} \
+          --vault-token=$${VAULT_TOKEN} \
+          --cluster-id=g8s \
+          --common-name=${ETCD_DOMAIN_NAME} \
+          --ttl=8760h \
+          --crt-file=/etc/kubernetes/ssl/etcd/server-crt.pem \
+          --ip-sans=127.0.0.1,${DEFAULT_IPV4} \
+          --alt-names=localhost \
+          --key-file=/etc/kubernetes/ssl/etcd/server-key.pem \
+          --ca-file=/etc/kubernetes/ssl/etcd/server-ca.pem); \
+        done; \
+        [ -z "$result" ] && echo "Failed to issue etcd certs." && exit 1 || echo "Successfully issued etcd certs.";'
       ExecStartPost=/bin/cp /etc/kubernetes/ssl/etcd/server-crt.pem /etc/kubernetes/ssl/etcd/client-crt.pem
       ExecStartPost=/bin/cp /etc/kubernetes/ssl/etcd/server-ca.pem /etc/kubernetes/ssl/etcd/client-ca.pem
       ExecStartPost=/bin/cp /etc/kubernetes/ssl/etcd/server-key.pem /etc/kubernetes/ssl/etcd/client-key.pem
@@ -2128,6 +2144,10 @@ systemd:
       ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl/
       ExecStartPre=/bin/bash -c "while ! curl -q --silent -o /dev/null https://${VAULT_DOMAIN_NAME};  do sleep 2s;echo wait for Vault;done;"
       ExecStartPre=/bin/bash -c '\
+        RETRY=3;\
+        while [ -z "$rsa_key"] && [ $RETRY -gt 0 ]; do\
+        sleep 2s; echo "trying to get g8s_sa_sign_key...";\
+        let RETRY=$RETRY-1;\
         export rsa_key=$(\
         docker run --rm -i\
         -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt\
@@ -2138,8 +2158,9 @@ systemd:
         quay.io/giantswarm/vault:0.9.3\
         read -field=key secret/g8s_sa_sign_key 2>/dev/null\
        );\
+       done;\
        [ -z "$rsa_key" ] && echo "Failed to fetch g8s_sa_key" && exit 1 || echo "Sucesfully retrieved g8s_sa_key";\
-        echo -e "-----BEGIN RSA PRIVATE KEY-----\n$rsa_key\n-----END RSA PRIVATE KEY-----" > /etc/kubernetes/ssl/service-account-key.pem'
+       echo -e "-----BEGIN RSA PRIVATE KEY-----\n$rsa_key\n-----END RSA PRIVATE KEY-----" > /etc/kubernetes/ssl/service-account-key.pem'
       ExecStart=/usr/bin/docker run \
       --net=host \
       -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt \
@@ -2156,41 +2177,6 @@ systemd:
       --alt-names=localhost,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.local\
       --key-file=/etc/kubernetes/ssl/apiserver-key.pem \
       --ca-file=/etc/kubernetes/ssl/apiserver-ca.pem
-
-      [Install]
-      WantedBy=multi-user.target
-  - name: k8s-scheduler.service
-    enabled: true
-    contents: |
-      [Unit]
-      Description=k8s-scheduler Service
-      StartLimitIntervalSec=0
-      Requires=k8s-setup-network-env.service docker.service
-      After=k8s-setup-network-env.service docker.service
-
-      [Service]
-      Restart=always
-      RestartSec=0
-      TimeoutStopSec=10
-      EnvironmentFile=/etc/network-environment
-      Environment="IMAGE=quay.io/giantswarm/hyperkube:v1.10.2"
-      Environment="NAME=%p.service"
-      Environment="NETWORK_CONFIG_CONTAINER="
-      ExecStartPre=/usr/bin/docker pull $IMAGE
-      ExecStartPre=-/usr/bin/docker stop -t 10 $NAME
-      ExecStartPre=-/usr/bin/docker rm -f $NAME
-      ExecStart=/usr/bin/docker run --rm --net=host --name $NAME \
-      -v /etc/kubernetes/ssl/:/etc/kubernetes/ssl/ \
-      -v /etc/kubernetes/config/:/etc/kubernetes/config/ \
-      $IMAGE \
-      /hyperkube scheduler \
-      --master=https://${API_DOMAIN_NAME}:443 \
-      --logtostderr=true \
-      --v=2 \
-      --profiling=false \
-      --kubeconfig=/etc/kubernetes/config/scheduler-kubeconfig.yaml
-      ExecStop=-/usr/bin/docker stop -t 10 $NAME
-      ExecStopPost=-/usr/bin/docker rm -f $NAME
 
       [Install]
       WantedBy=multi-user.target
