Azure master roll (#575)
* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

* Use scale up and delete old strategy for Azure MC rollouts.

diff --git a/templates/files/conf/attach-etcd-disk b/templates/files/conf/attach-etcd-disk
--- a/templates/files/conf/attach-etcd-disk
+++ b/templates/files/conf/attach-etcd-disk
@@ -25,10 +25,16 @@ resourceid="$(echo "$metadata" | jq -r .compute.resourceId)"
 # Extract instance ID (a number) from the resource ID.
 INSTANCEID="$(echo $resourceid | grep -Eo '[0-9]+$')"
 
+# Run a container with azure-cli.
+docker kill azure-cli || true
+docker rm azure-cli || true
+docker run --name azure-cli -d mcr.microsoft.com/azure-cli sleep infinity
+docker exec azure-cli az login --identity || (echo "Failed logging in with Azure cli."; exit 1)
+
 run_az_cmd () {
   cmd="$1"
 
-  docker run --rm mcr.microsoft.com/azure-cli bash -c "az login --identity 2>&1 >/dev/null && $cmd"
+  docker exec azure-cli $cmd
 }
 
 if [ -f "$DISK" ] || [ -h "$DISK" ]
@@ -63,7 +69,7 @@ else
   # list all disks with tag GiantSwarmRole == "etcd" and having a GiantSwarmEtcdID tag
   echo "Looking for available disks"
   # TODO discard disks with multi-attach feature enabled when az will support it
-  candidates="$(run_az_cmd "az disk list -g ${RESOURCEGROUP} | jq '. | map(select(.tags.GiantSwarmRole == \"etcd\" and .diskState == \"Unattached\" and (.tags | has(\"GiantSwarmEtcdID\"))))'")"
+  candidates="$(run_az_cmd "az disk list -g ${RESOURCEGROUP}" | jq '. | map(select(.tags.GiantSwarmRole == "etcd" and .diskState == "Unattached" and (.tags | has("GiantSwarmEtcdID"))))')"
 
   if [ "$candidates" == "[]" ]
   then
@@ -149,3 +155,6 @@ master_id_file="${MOUNTPOINT}/master-id"
 echo "Writing master ID ${MASTER_ID} to ${master_id_file}"
 
 echo "MASTER_ID=${MASTER_ID}" >$master_id_file
+
+docker kill azure-cli || true
+docker rm azure-cli || true
