Remove static vault node token references (#448)
* Remove static vault node token references

* Fail on error getting vault token

* Fix azure role

* Pass node type to vault script

* Add role assignment dependency

* Add module dependency on vault

* Add wait resource

* fix

diff --git a/templates/files/conf/get-vault-token b/templates/files/conf/get-vault-token
--- a/templates/files/conf/get-vault-token
+++ b/templates/files/conf/get-vault-token
@@ -1,15 +1,30 @@
 #!/bin/sh
 
-set -uxo pipefail
+set -euxo pipefail
 
 # Vault configuration
 export VAULT_ADDR=https://{{ .VaultDomainName }}
 export CLUSTER_NAME={{ .ClusterName }}
 
+role=$1
+
+if [ "${role}" = "" ]; then
+    echo "Node role can't be empty"
+    exit 1
+fi
+
 # Azure metadata
 jwt="$(curl -s 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com' -H Metadata:true | jq -r '.access_token')"
 subscription_id=$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .subscriptionId')
-vm_name="$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .name')"
+vm_parameter=""
+
+if [ "${role}" = "master" ]; then
+    vm_name="$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .name')"
+    vm_parameter="vm_name=${vm_name}"
+else
+    vmss_name="${CLUSTER_NAME}-workers"
+    vm_parameter="vmss_name=${vmss_name}"
+fi
 
 login_info=$(\
     docker run --rm -i\
@@ -19,7 +34,8 @@ login_info=$(\
     -e VAULT_ADDR\
     -e CLUSTER_NAME\
     quay.io/giantswarm/vault:1.6.1\
-    write auth/azure/login role="management-node" jwt=${jwt} subscription_id=${subscription_id} resource_group_name=${CLUSTER_NAME} vm_name=${vm_name} -format=json);
+    write auth/azure/login role="management-node"\
+      jwt=${jwt} subscription_id=${subscription_id} resource_group_name=${CLUSTER_NAME} ${vm_parameter} -format=json);
 
 vault_token=$(echo ${login_info} | jq -r .auth.client_token)
 echo "VAULT_TOKEN=${vault_token}" > /etc/tokens/node
