Label namespaces with name label

diff --git a/templates/master.yaml.tmpl b/templates/master.yaml.tmpl
--- a/templates/master.yaml.tmpl
+++ b/templates/master.yaml.tmpl
@@ -2157,6 +2157,19 @@ storage:
 
             while ! curl --output /dev/null --silent --head --insecure "https://{{ .APIDomainName }}"; do sleep 1 && echo 'Waiting for master'; done
 
+            # label namespaces (required for network egress policies)
+            NAMESPACES="default giantswarm kube-system" 
+            for namespace in ${NAMESPACES}
+            do
+                while
+                    $KUBECTL label namespace ${namespace} name=${namespace}
+                    [ "$?" -ne "0" ]
+                do
+                    echo "failed to label namespace ${namespace}, retrying in 5 sec"
+                    sleep 5s
+                done
+            done
+
             # apply Security bootstrap (RBAC and PSP)
             SECURITY_FILES="rbac-roles.yaml
              rbac-bindings.yaml
