Fix labeling loop

diff --git a/templates/master.yaml.tmpl b/templates/master.yaml.tmpl
--- a/templates/master.yaml.tmpl
+++ b/templates/master.yaml.tmpl
@@ -2176,11 +2176,16 @@ storage:
             for namespace in ${NAMESPACES}
             do
                 while
-                    $KUBECTL label namespace ${namespace} name=${namespace}
+                    $KUBECTL get namespaces -l name=${namespace} | grep ${namespace}
                     [ "$?" -ne "0" ]
                 do
-                    echo "failed to label namespace ${namespace}, retrying in 5 sec"
-                    sleep 5s
+                    while
+                        $KUBECTL label namespace ${namespace} name=${namespace}
+                        [ "$?" -ne "0" ]
+                    do
+                        echo "failed to label namespace ${namespace}, retrying in 5 sec"
+                        sleep 5s
+                    done
                 done
             done
 
