Fix labeling loop (#250)
* Fix labeling loop

* Fix labeling

diff --git a/templates/master.yaml.tmpl b/templates/master.yaml.tmpl
--- a/templates/master.yaml.tmpl
+++ b/templates/master.yaml.tmpl
@@ -2175,13 +2175,15 @@ storage:
             NAMESPACES="default giantswarm kube-system" 
             for namespace in ${NAMESPACES}
             do
-                while
-                    $KUBECTL label namespace ${namespace} name=${namespace}
-                    [ "$?" -ne "0" ]
-                do
-                    echo "failed to label namespace ${namespace}, retrying in 5 sec"
-                    sleep 5s
-                done
+                if ! $KUBECTL get namespaces -l name=${namespace} | grep ${namespace}; then
+                    while
+                        $KUBECTL label namespace ${namespace} name=${namespace}
+                        [ "$?" -ne "0" ]
+                    do
+                        echo "failed to label namespace ${namespace}, retrying in 5 sec"
+                        sleep 5s
+                    done
+                fi
             done
 
             # apply Security bootstrap (RBAC and PSP)
