Use kube-proxy config in configmap

diff --git a/templates/master.yaml.tmpl b/templates/master.yaml.tmpl
--- a/templates/master.yaml.tmpl
+++ b/templates/master.yaml.tmpl
@@ -1283,6 +1283,24 @@ storage:
           metadata:
             name: kube-proxy
             namespace: kube-system
+    - path: /srv/kube-proxy-cm.yaml
+      filesystem: root
+      mode: 0644
+      contents:
+        inline: |
+          kind: ConfigMap
+          apiVersion: v1
+          metadata:
+            name: kube-proxy
+            namespace: kube-system
+          data:
+            kube-proxy-config.yaml: |
+              apiVersion: kubeproxy.config.k8s.io/v1alpha1
+              clientConnection:
+                kubeconfig: /etc/kubernetes/config/kube-proxy-kubeconfig.yaml
+              kind: KubeProxyConfiguration
+              mode: ipvs
+              resourceContainer: /kube-proxy
     - path: /srv/kube-proxy-ds.yaml
       filesystem: root
       mode: 0644
@@ -1343,11 +1361,14 @@ storage:
                   securityContext:
                     privileged: true
                   volumeMounts:
+                  - name: kube-proxy-config
+                    mountPath: /etc/kubernetes/config/kube-proxy-config.yaml
+                    readOnly: true
                   - mountPath: /etc/ssl/certs
                     name: ssl-certs-host
                     readOnly: true
-                  - mountPath: /etc/kubernetes/config/
-                    name: config-kubernetes
+                  - mountPath: /etc/kubernetes/config/kube-proxy-kubeconfig.yaml
+                    name: kube-proxy-kubeconfig
                     readOnly: true
                   - mountPath: /etc/kubernetes/ssl
                     name: ssl-certs-kubernetes
@@ -1356,9 +1377,17 @@ storage:
                     name: lib-modules
                     readOnly: true
                 volumes:
+                - name: kube-proxy-config
+                  configMap:
+                    name: kube-proxy
+                    namespace: kube-system
+                    items:
+                    - key: kube-proxy-config.yaml
+                      key: kube-proxy-config.yaml
                 - hostPath:
-                    path: /etc/kubernetes/config/
-                  name: config-kubernetes
+                    path: /etc/kubernetes/config/kube-proxy-kubeconfig.yaml
+                    type: File
+                  name: kube-proxy-kubeconfig
                 - hostPath:
                     path: /etc/kubernetes/ssl/
                   name: ssl-certs-kubernetes
@@ -2013,6 +2042,20 @@ storage:
                 done
             done
 
+            # apply kube-proxy
+            KUBE_PROXY_MANIFESTS="kube-proxy-sa.yaml kube-proxy-cm.yaml kube-proxy-ds.yaml"
+
+            for manifest in $KUBE_PROXY_MANIFESTS
+            do
+                while
+                    /usr/bin/docker run --net=host --rm -v /srv:/srv $KUBECTL apply -f /srv/$manifest
+                    [ "$?" -ne "0" ]
+                do
+                    echo "failed to apply /srv/$manifest, retrying in 5 sec"
+                    sleep 5s
+                done
+            done
+
             # apply calico CNI
             CALICO_FILE="calico-all.yaml"
 
@@ -2038,7 +2081,7 @@ storage:
             done
 
             # apply k8s addons
-            MANIFESTS="kube-proxy-sa.yaml kube-proxy-ds.yaml default-storage-class.yaml coredns-all.yaml default-backend-dep.yaml default-backend-svc.yaml ingress-controller-cm.yaml ingress-controller-sa.yaml ingress-controller-dep.yaml ingress-controller-svc.yaml"
+            MANIFESTS="default-storage-class.yaml coredns-all.yaml default-backend-dep.yaml default-backend-svc.yaml ingress-controller-cm.yaml ingress-controller-sa.yaml ingress-controller-dep.yaml ingress-controller-svc.yaml"
 
             for manifest in $MANIFESTS
             do
@@ -2069,7 +2112,7 @@ storage:
           vnetName: {{ .AzureVnetName }}
           routeTableName: {{ .AzureRoutable }}
     {{- end }}
-    - path: /etc/kubernetes/config/proxy-kubeconfig.yaml
+    - path: /etc/kubernetes/config/kube-proxy-kubeconfig.yaml
       filesystem: root
       mode: 0644
       contents:
@@ -2144,7 +2187,7 @@ storage:
         inline: |
           apiVersion: kubeproxy.config.k8s.io/v1alpha1
           clientConnection:
-            kubeconfig: /etc/kubernetes/config/proxy-kubeconfig.yaml
+            kubeconfig: /etc/kubernetes/config/kube-proxy-kubeconfig.yaml
           kind: KubeProxyConfiguration
           mode: ipvs
           resourceContainer: /kube-proxy
