Create giantswarm namespace if it doesn't exist (#249)

diff --git a/templates/master.yaml.tmpl b/templates/master.yaml.tmpl
--- a/templates/master.yaml.tmpl
+++ b/templates/master.yaml.tmpl
@@ -2157,6 +2157,20 @@ storage:
 
             while ! curl --output /dev/null --silent --head --insecure "https://{{ .APIDomainName }}"; do sleep 1 && echo 'Waiting for master'; done
 
+            # Create giantswarm namespace
+            while
+                $KUBECTL get namespace giantswarm
+                [ "$?" -ne "0" ]
+            do
+                while
+                    $KUBECTL create namespace giantswarm
+                    [ "$?" -ne "0" ]
+                do
+                    echo "failed to create namespace giantswarm, retrying in 5 sec"
+                    sleep 5s
+                done
+            done
+
             # label namespaces (required for network egress policies)
             NAMESPACES="default giantswarm kube-system" 
             for namespace in ${NAMESPACES}
