Update k8s addons with rbac and psp

diff --git a/cloud-config/master.yaml.tmpl b/cloud-config/master.yaml.tmpl
--- a/cloud-config/master.yaml.tmpl
+++ b/cloud-config/master.yaml.tmpl
@@ -1422,6 +1422,24 @@ write_files:
       # wait for healthy master
       while [ "$(/usr/bin/docker run --net=host --rm $KUBECTL get cs | grep Healthy | wc -l)" -ne "3" ]; do sleep 1 && echo 'Waiting for healthy k8s'; done
 
+      # apply Security bootstrap (RBAC and PSP)
+      SECURITY_FILES="rbac-roles.yaml\
+        rbac-bindings.yaml\
+        psp-policies.yaml\
+        psp-roles.yaml\
+        psp-bindings.yaml"
+
+      for manifest in $SECURITY_FILES
+      do
+          while
+              /usr/bin/docker run --net=host --rm -v /srv:/srv $KUBECTL apply -f /srv/$manifest
+              [ "$?" -ne "0" ]
+          do
+              echo "failed to apply /srv/$manifest, retrying in 5 sec"
+              sleep 5s
+          done
+      done
+
       # apply calico CNI
       CALICO_FILE="calico-all.yaml"
 
@@ -1447,7 +1465,7 @@ write_files:
       done
 
       # apply k8s addons
-      MANIFESTS="default-storage-class.yaml coredns-all.yaml default-backend-dep.yml default-backend-svc.yml ingress-controller-cm.yml ingress-controller-dep.yml ingress-controller-svc.yml kube-lego-cm.yml kube-lego-dep.yml"
+      MANIFESTS="default-storage-class.yaml kubedns-all.yaml default-backend-dep.yml default-backend-svc.yml ingress-controller-cm.yml ingress-controller-sa.yml ingress-controller-dep.yml ingress-controller-svc.yml kube-lego-cm.yml kube-lego-sa.yml kube-lego-dep.yml"
 
       for manifest in $MANIFESTS
       do
